feat: 비교 페이지 컴포넌트 구현, 비교 기능 구현중
mju-likelion/hackathon-team1-web pull request #10
Opened 2023-08-08 11:30 UTC by Jake-Kim38

비교 페이지 상단 컴포넌트 구현 완료했습니다.
비교 기능(보험 삭제) 구현 중입니다.

2023-08-08 13:17 UTC, Bhanjo reviewed
슬랙에 올려놓은 것에 대한 답변은 스레드 댓글로 남겼습니다~
아직까지 리뷰할 것은 없네요!

2023-08-08 13:17 UTC, Bhanjo commented on src/pages/Compare.jsx
> +  loanArr.push(JSON.parse(loadedThirdData));
목업데이터는 데이터를 분리해주세요~ 파일을 만들어도 좋고 컴포넌트 외부에 넣어도 좋습니다

2023-08-08 15:32 UTC, Bhanjo commented on src/pages/Compare.jsx
> +  };
지금 state를 세 개나 쓰고 있어서 관리가 매우 힘들어보이고 하드코딩이 되어있어요
저라면 `compareInsurence`라는 배열로 된 state를 만들고 관리했을 것 같네요

```
const [compareInsurence, setCompareInsurence] = useState(localStorage.getItem(insurences))
```

마찬가지로 localStorage를 꼭 firstData, secondData와 같이 각각 독립적인 storage를 할당할 필요 없습니다!
로컬스토리지 하나를 써서 key는 insurence로 하고 value는 아래와 같이 하면 관리하기 더 쉽습니다.
```
[
  {
    id: '롯데손해보험',
    price: 1000,
    notice: '대충설명',
    // 기타 정보들
  },
  {
    id: '삼성손해보험',
    price: 3000,
    notice: '대충설명',
    // 기타 정보들
  },
  {
    id: '롯데손해보험',
    price: 1000,
    notice: '대충설명',
    // 기타 정보들
  }
]
```

좀 더 확장하자면 보험 비교를 꼭 세 개만 한다고 생각하는 것은 매우 위험한 생각이에요
나중에 2개 비교가 될 수 있고 10개 비교가 될 수 있어요
그럴때마다 localStorage를 각각 생성하고 key를 first, second, third,... 를 할 수 없어요 확장성 유지보수 가독성 모두 챙기지 못하는 코드에요

코드를 짤때는 항상 확장성을 생각해주세요 특히 `개수`에 갇혀있는 생각은 절대 하면 안됩니다!

2023-08-08 15:36 UTC, Bhanjo commented
코드를 짤 때 지금은 계속 `어떻게든 돌아가게 만들기`에 너무 치중되어있어보여요!
만들고나서 꼭 `이게 유지보수하기 편한가`, `이름은 이게 맞을까`, `지금 구조가 확장하기 편한가`를 생각해주세요

2023-08-09 00:16 UTC, Bhanjo commented on src/pages/Compare.jsx
> +  };
아뇨 이름은 제가 그냥 정한거에요

2023-08-09 06:20 UTC, harksu requested changes
조금만 더 고민해봅시다 🔥

2023-08-09 06:20 UTC, harksu commented on src/components/UpsideCompareBox.jsx
> +  const { id, loanName, company } = testData;
id는 어디서 받아오는지 의도를 한번 서술해주세용

2023-08-09 06:20 UTC, harksu commented on src/pages/Compare.jsx
> +    localStorage.getItem("insurances")
만약에 없으면?

2023-08-09 06:20 UTC, harksu commented on src/pages/Compare.jsx
> +  };
고민해야 할 포인트 
1. 과연 해당 배열의 길이가 3보다 큰 값인지 고민하는게 먼저일까요?
2. 두 번째 컨디션에서 loanArr[i]가 맞는 접근일까요? 어차피 반복문의 조건이 해당 배열의 길이 만큼 수행되는데?
3. 1,2로 인해서 해당 코드의 가독성이 현저하게 떨어지고 반복되는 부분이 발생합니다. 조금 더 정리하면 좋을 것 같아요!

2023-08-09 06:20 UTC, harksu commented on src/pages/Compare.jsx
> +        <UpsideArea>{rendering()}</UpsideArea>
```suggestion
        <UpsideArea>{rendering}</UpsideArea>
```

2023-08-09 06:20 UTC, harksu commented on src/pages/Compare.jsx
> +        <UpsideArea>{rendering()}</UpsideArea>
https://ko.legacy.reactjs.org/docs/faq-functions.html
☝️  참고!

2023-08-09 09:12 UTC, Jake-Kim38 commented on src/components/UpsideCompareBox.jsx
> +  const { id, loanName, company } = testData;
서버 API 상에서 infoId 라는 각 보험 객체의 ID 값이 있는데, 얘를 넘겨받으려는 목적이었습니다

2023-08-09 09:18 UTC, Jake-Kim38 commented on src/pages/Compare.jsx
> +  };
1. 원래는 else 부분의 코드만 있었는데, 이러면 보험이 3개가 있는 경우 빈 컴포넌트 하나가 더 생겨서 화면을 넘기더라구요. 그래서 배열의 길이가 3보다 큰 경우 무조건 보험 컴포넌트 3개만 나오도록 제한을 두고자 이렇게 짰습니다.
2. 얘는 보험 개수가 3개 미만일 경우 무조건 비었음을 보여주는 컴포넌트 하나를 더 추가해서 PR 영상처럼 작동하도록 짰습니다. 즉 loanArr[i]를 검사했을 때 값이 없다면 빈 컴포넌트를 보여주기 위해 loanArr[i] 조건을 걸었습니다.

좀 설명이 난잡하긴 한데, 사실 결론은 말하신 대로 해당 코드의 가독성을 향상시키기 위해 쓸 수 있는 방법이 무엇이 있는지에 대해 힌트를 주셨음 합니다 ㅎㅎ

2023-08-09 09:20 UTC, Jake-Kim38 commented on src/pages/Compare.jsx
> +    localStorage.getItem("insurances")
insurances 라는 키가 로컬스토리지에 없는 경우를 말하신 거라면,
로컬스토리지가 빈 상태에서 비교함 페이지를 접근했을 때 이를 막는 로직을 추가하면 되지 않을까 생각합니다.
(비교함 버튼에 추가하면 될 것 같은데.. 아닐까요? ㅎㅎ)

2023-08-09 15:51 UTC, Bhanjo commented on src/pages/Compare.jsx
> +  };
이 문제는 for문 사용 하지 말고 forEach, map 함수만을 이용해 구현해보세요!

2023-08-10 00:26 UTC, Bhanjo reviewed
리뷰가 좀 빡세긴 합니다! 만약에 무리일 것 같으면 언제든 말씀해주세요~

2023-08-10 00:26 UTC, Bhanjo commented on src/components/CompareDetailBox.jsx
> +      result.push(<SecondContent>{item}</SecondContent>);
first, second, third라는 네이밍을 없애주세요! 하나의 content컴포넌트를 사용해주세요
지금 컴포넌트 보면 스타일은 margin-left차이이고 나머진 다 똑같은데 조건부 스타일을 이용하면 이걸 하나의 컴포넌트로 만들면서 의도를 잘 표현할 수 있습니다

2023-08-10 00:26 UTC, Bhanjo commented on src/components/CompareDetailBox.jsx
> +          rendering(`${item.startAge}~${item.endAge}세`, idx)
지금 가입연령에 대한 map, 보험료에 대한 map 등 여러번 map을 호출하는데 이를 간단히 바꾸자면 flex를 column 속성으로 만들고 map을 한 번 사용하면서 연령, 보험료, 가입형태를 한번에 표현할 수 있어요
그럼 렌더링 단위는 row단위가 아니라 column 단위로 할 수 있습니다!

2023-08-10 00:26 UTC, Bhanjo commented on src/pages/Compare.jsx
> +    loanArr.map((item, idx) => {
map 함수는 map을 실행한 결과를 반환합니다 따라서 result[idx] = ~ 할 필요 없이
result = loanArr.map~ 으로 할 수 있습니다

2023-08-10 00:26 UTC, Bhanjo commented on src/pages/Compare.jsx
> +      if (idx !== 2) {
idx가 2가 아니면 현재 인덱스 다음에 비어있는 카드를 렌다링하는데,
1일 때 2에 비어있는 카드
2일 때 건너뜀
3일 때 4에 비어있는 카드
이렇게 되고있네요
그럼 결과는
카드 카드 카드 비어있는카드
총 네 개가 나와요. 의도하지 읺는 네 번째 카드가 생깁니다
이 네 번째 카드가 생기지 않게 로직을 바꿔주세요!

2023-08-10 00:34 UTC, Bhanjo commented on src/pages/Compare.jsx
> +    localStorage.getItem("insurances")
네 맞아요~ getitem 해서 없다면 빈 배열을 할달하도록 해주세요
힌논리언산자 단축펑가를 사용해보세오~

2023-08-10 01:25 UTC, harksu requested changes
바꿔봅시다 🔥 
조금만 더 빠르게 작업을 해주세요! 얼마 안남았습니다

2023-08-10 01:25 UTC, harksu commented on src/components/CompareDetailBox.jsx
> +      result.push(<SecondContent>{item}</SecondContent>);
☝️ 이건 꼭 해주세요 어차피 index를 파라미터로 사용하니까 조건부 스타일에 index를 이용해서 사용하면 불필요한 로직을 제외할 수 있습니다.

2번 양보해서, 만약 전부 필요한 content라고 하더라도 네이밍이 부적절해요!

2023-08-10 01:25 UTC, harksu commented on src/pages/Compare.jsx
> +    localStorage.getItem("insurances")
꼭 추가하세요! 자바스크립트는 개발자의 실수에 대해 굉장히 너그러운 편이라서, 런타임 에러에 주의해야 합니다!

2023-08-10 03:19 UTC, Jake-Kim38 commented on src/components/CompareDetailBox.jsx
> +          rendering(`${item.startAge}~${item.endAge}세`, idx)
누구의 flex를 column으로 바꿔야 하나요??

2023-08-10 03:31 UTC, Jake-Kim38 commented on src/pages/Compare.jsx
> +      if (idx !== 2) {
idx <= 2 로 바꾸면 될까요??
사실 여기가 잘 이해가 가지 않습니다. 도와주세요 ㅠㅠ

2023-08-10 03:32 UTC, Jake-Kim38 commented on src/pages/Compare.jsx
> +    loanArr.map((item, idx) => {
result = loanArr.map~ 을 했을 때, 배열의 특정 idx 값을 바꿀 수 있나요?

2023-08-10 03:35 UTC, Bhanjo commented on src/components/CompareDetailBox.jsx
> +          rendering(`${item.startAge}~${item.endAge}세`, idx)
가입연령 보험료 얘네들을 묶는 컨테이너를 flex로 묶어주세요
이 컨테이너는 보험 1개의 정보만 가지고있다고 생각해주세요
그럼 map으로 컨테이너를 loan 개수만큼 출력하면 되겠네요~

2023-08-10 03:36 UTC, Bhanjo commented on src/pages/Compare.jsx
> +    loanArr.map((item, idx) => {
특정 idx의 값을 바꾸는 것은 조금 고민하면 이 로직에 없어도 되는 부분이에요 로직을 좀 더 고민하면 될 것 같습니다

2023-08-10 03:38 UTC, Bhanjo commented on src/pages/Compare.jsx
> +      if (idx !== 2) {
항상 이야기하는거지만 너무 개수에 묶여있는 생각을 하고있어요
값이 있으면 출력 없으면 빈 카드 출력 이것만 생각하면 되는데 계속 무조건 3개가 있어여된다는 생각에 사로잡혀있어요
그냥 3개가 됐던 100개가 됐던 배열에 값 무조건 출력한다 생각해주세요
극단적으로 idx라는 개념을 머릿속에서 지운채로 개발해보세요

2023-08-10 16:42 UTC, Bhanjo commented on src/components/CompareDetailBox.jsx
> +        style={idx === 0 ? { marginLeft: "85px" } : { marginLeft: "248px" }}
이거 바꿔달라했는데 바꾸지 않았네요.. 안바꾼 이유가 있을까요?

2023-08-10 16:42 UTC, Bhanjo commented on src/components/CompareDetailBox.jsx
> +        {compareInsurance.map((item, idx) => rendering(item.type, idx))}
key prop 에러 발생될 것으로 예상되는데 이에 대한 처리 해주세요!

2023-08-10 17:42 UTC, Jake-Kim38 commented on src/components/CompareDetailBox.jsx
> +        style={idx === 0 ? { marginLeft: "85px" } : { marginLeft: "248px" }}
엇 충돌해결하다가 예전걸로 바뀌었나봐요
바로 수정하겠습니다 ㅠㅠ

2023-08-11 03:01 UTC, Jake-Kim38 commented on src/components/CompareDetailBox.jsx
> +        style={idx === 0 ? { marginLeft: "85px" } : { marginLeft: "248px" }}
형 말해주신대로 space-between 등 써서 구현해봤다가, 보험이 3개에서 2개로 줄었을 때
해당 스타일을 강제로 적용하다 보니 간격이 깨져서 나오더라구요. 그래서 아이템 간 간격을 유지하려고
해당 코드를 유지시켰습니다.

2023-08-11 06:17 UTC, Bhanjo commented on src/components/CompareDetailBox.jsx
> +        style={idx === 0 ? { marginLeft: "85px" } : { marginLeft: "248px" }}
그럼 제가 말했던 styled component 조건부 스타일링으로 바꿔주세요~

2023-08-11 14:47 UTC, harksu approved these changes
살짝 아쉽긴한데, 우선 급하니까 머지해도 괜찮을 것 같습니다 :)

2023-08-11 14:47 UTC, harksu commented on src/components/UpsideEmptyBox.jsx
> +      <SelectButton>검색 결과 페이지로</SelectButton>
라우터는 일부러 안붙인건가욤?

2023-08-11 14:47 UTC, harksu commented on src/pages/Compare.jsx
> +    JSON.parse(localStorage.getItem("insurances")) || []
보통 이런 값들은 state보다 위에서 선언하고 그 변수를 state에 담습니다.
너무 길면 가독성이 안좋아요!

```
const insuraceArray =  JSON.parse(localStorage.getItem("insurances") 
const [compareInsurance, setCompareInsurance] = useState(insuraceArray)
```

그리고 문맥을 보면 아이템이 없을 경우는 빈배열을 선언하려고 한 것 같은데 맞을까요 ?

이게 맞다면 

`const [compareInsurance, setCompareInsurance] = useState(insuraceArray) || [] `인데,
빈 배열이` [compareInsurance, setCompareInsurance`]에 들어간 상태에서 setCompareInsurance 부르면 바로 런타임 에러 터질텐데..?

2023-08-11 14:47 UTC, harksu commented on src/pages/Compare.jsx
> +        <UpsideArea>{rendering(compareInsurance)}</UpsideArea>
```suggestion
        <UpsideArea>{()=> rendering(compareInsurance)}</UpsideArea>
```

2023-08-11 14:47 UTC, harksu commented on src/pages/Compare.jsx
> +const MAX_COMPARE_AMOUNT = 3;
이런거 좋습니다. 하지만 목업 상수를 선언할 땐 **가장 위에 선언해주세요**!

2023-08-12 08:17 UTC, merged