feat: 검색결과 페이지 초기 구현 완료
mju-likelion/hackathon-team1-web pull request #4
Opened 2023-08-02 14:06 UTC by Jake-Kim38

* 검색 결과 페이지 초기 구현 완료했습니다.
*  디자인 틀만 잡았기 때문에 특별한 이슈는 아직 없다고 생각합니다.
* 추후에 서버에서 질문에 맞는 데이터들을 가져와서 뿌려주기만 하면 될 것 같습니다.

2023-08-02 23:16 UTC, harksu reviewed
작업량이 많지가 않아서, 제대로 된 리뷰는 로직이 좀 들어가야 할 수 있을 것 같아욤

2023-08-02 23:16 UTC, harksu commented on src/components/InsuranceBox.js
> +const InsuranceBox = ({ loandata }) => {
구조분해할당을 애용합시다 🔥

2023-08-02 23:16 UTC, harksu commented on src/components/SmallButton.js
> +    cursor: pointer;
button은 기본이 포인터 속성일텐데...?
그리고 보통 버튼과 같이 일반적으로 사용되는 컴포넌트들은 common폴더나 component폴더에서 선언하고 재사용하는게 좋은 아키텍처입니다 :)

2023-08-02 23:16 UTC, harksu commented on src/pages/Search.js
> +import kb from "../assets/kb.svg";
kb는 올바른 이름이 아닌 것 같고, svg로 리액트 컴포넌트를 반환해 사용할 땐 PascalCase로 사용합시다!

2023-08-02 23:16 UTC, harksu commented on src/pages/Search.js
> +    age: "15~99",
string타입보다는 15,~,99로 분리하는게 더 나을 것 같아요:) 
(서버에서 해당 형식으로 반환해준다는 확신이 있으면 관계가 없긴하지만, 보통 시작날짜 끝나는 날짜를 반환해줍니다)

2023-08-03 16:12 UTC, Bhanjo reviewed
모든 스타일을 div로 처리하는 것은 매우 안좋은 방법입니다!
div, span, p, h1 등등 각자 역할에 맞는 스타일을 써주세요!

2023-08-03 16:12 UTC, Bhanjo commented on src/components/InsuranceBox.jsx
> +          <LoanImage src={img} />
이미지에는 항상 `alt`를 기억해주세요~

2023-08-03 16:12 UTC, Bhanjo commented on src/components/InsuranceBox.jsx
> +          </BottomArea>
AgeTitle, CostTitle, JoinTitle 모두 같은 스타일인데 굳이 분리한 이유가 있을까요?
css를 보면 공통화가 이루어져있지 않고 모두 따로따로 처리한 느낌이 강합니다!
어떤 부분은 `공통화` 할 수 있을지 고민이 필요해보여요

~title, ~unit은 같은 text style을 공유하니까 이를 묶어주고 가운데에 있는 구분자는 before 속성등을 이용해 충분히 구현 가능하다 생각합니다! 지금 css 스타일은 확장성, 가독성 측면에서 떨어져요!

2023-08-03 16:12 UTC, Bhanjo commented on src/components/SmallButton.jsx
> +  return <Button onClick={(e) => clickevent(e)}>{text}</Button>;
event 객체는 굳이 파라미터를 넘기지 않아도 됩니다! `onClick={clickEvent}`로 해도 event 객체가 넘어갑니다!
또한, `onClick`이나 `handleClick`처럼 이 props가 함수라는 것을 명확하게 표현하는 이름을 써주세요!

2023-08-03 16:12 UTC, Bhanjo commented on src/pages/Search.jsx
> +const loandata = [
샘플 데이터는 샘플 데이터라는 표시를 해주세요! 또한 상수는 PARCAL_CASE를 써주세요

2023-08-03 16:12 UTC, Bhanjo commented on src/pages/Search.jsx
> +            <InsuranceBox key={item.main} id={idx} loandata={item} />
여기에 id를 부여한 이유가 있나요?? id를 쓰는 곳이 없어보입니다!

2023-08-03 16:12 UTC, Bhanjo commented on src/pages/Search.jsx
> +            <RightCount>검색 결과</RightCount>
이거는 text로 보이는데 div로 처리한 이유가 있을까요?? 또한 text에 width을 준 이유가 있나요?

2023-08-03 16:14 UTC, harksu requested changes
🔥

2023-08-03 16:14 UTC, harksu commented on src/App.jsx
> +    <>
불필요한 fragment 태그는 지양합시다 :)

2023-08-03 16:14 UTC, harksu commented on src/components/InsuranceBox.jsx
> +const InsuranceBox = ({ loandata }) => {
```suggestion
const InsuranceBox = ({ loanData }) => {
```

2023-08-03 16:14 UTC, harksu commented on src/components/InsuranceBox.jsx
> +        <LeftContainer>
보통 container 는 최외각을 감싸는 하나의 div component를 지칭하고는 합니다

2023-08-03 16:14 UTC, harksu commented on src/components/InsuranceBox.jsx
> +            </CostArea>
구조가 거의 유사한데, 분리를 고민해봐도 좋을 것 같아요!

2023-08-03 16:14 UTC, harksu commented on src/components/InsuranceBox.jsx
> +  justify-content: space-around;
space-around, space-between 같은 속성을 사용할 때는 확실하게 인지하고 주의해서 사용해주세요!

2023-08-03 16:14 UTC, harksu commented on src/components/InsuranceBox.jsx
> +const MainName = styled.div`
name은 보통 p태그를 사용하는게 보편적입니다

2023-08-03 16:14 UTC, harksu commented on src/components/InsuranceBox.jsx
> +const CostArea = styled.div`
ageArea랑 겹치죠? 물론 이름을 통해서 구분하겠다는게 안좋은 접근은 아니지만 같은 속성을 가지고 있는 컴포넌트를 생성하는게 올바른가에 대한 고민이 다소 필요해보입니다. styledArea라는 이름으로 통일해서 사용해도 무방하니까요 :)

2023-08-03 16:14 UTC, harksu commented on src/components/InsuranceBox.jsx
> +const CostArea = styled.div`
자세하게 모든 styled-component 를 보진 않을거지만, 단순히 사용되는 영역이 다르다고해서 굳이 다른 이름으로 같은 속성의 컴포넌트를 중복 선언할 필요는 없습니다!

2023-08-03 16:14 UTC, harksu commented on src/pages/Search.jsx
> +const loandata = [
보통 목업데이터, 상수는 UPPER_CASE를 사용합니다

2023-08-03 16:14 UTC, harksu commented on src/styles/Theme.jsx
> +export const Theme = {
theme파일이 왜 jsx일까요? 컴포넌트가 아닌데?

2023-08-04 02:20 UTC, Jake-Kim38 commented on src/components/InsuranceBox.jsx
> +          </BottomArea>
찾아보니까 before의 경우 ::before 이런식으로 쓰던데, 이거를 styled component로 쓰려면 어떻게 해야 하나요??
const DivLine = styled.before` 이런 식으로 하는게 맞나요??

2023-08-04 02:25 UTC, Jake-Kim38 commented on src/pages/Search.jsx
> +            <RightCount>검색 결과</RightCount>
p로 해도 되는군요..ㅎㅎ

2023-08-04 02:30 UTC, Jake-Kim38 commented on src/components/InsuranceBox.jsx
> +            </CostArea>
분리를 한다면 어떻게 할 수 있을까요..?? 감이 잘 안잡혀서.. map 같은걸 쓰라는 의미로 말하신 건가요??

2023-08-04 02:30 UTC, Jake-Kim38 commented on src/components/InsuranceBox.jsx
> +  justify-content: space-around;
지금 상황에선 문제가 없는 건가요?? 주의하라는 의미로만 말하신건가용??

2023-08-04 02:37 UTC, Jake-Kim38 commented on src/styles/Theme.jsx
> +export const Theme = {
'가끔 jsx문법을 쓰는 컴포넌트용 파일임을 표기하기위해 .jsx를 붙이는 경우가 있는데...'
구글링해보니 이런 말을 찾았는데, 이 이유가 맞나요??
그리고 jsx 파일은 리액트를 사용한 파일인 것이 맞나요??(순수 JS가 아닌 파일)
이게 맞다면 Theme 파일은 js인게 말이 되는거같아서요!

2023-08-04 03:47 UTC, Bhanjo commented on src/components/InsuranceBox.jsx
> +          </BottomArea>
&::before와 같이 사용하면됩니다!

2023-08-04 03:51 UTC, Jake-Kim38 commented on src/components/InsuranceBox.jsx
> +          </BottomArea>
`const DivLine = styled.&::before`
  width: 2px;
  height: 57px;
  background-color: ${({ theme }) => theme.colors.LIGHTGRAY};
  margin-left: 150px;
`;`
이런 식인가요?? &::before를 어디에 넣어야 할지 감이 안잡히네요 ㅎㅎ;;

2023-08-04 06:11 UTC, Bhanjo commented on src/components/InsuranceBox.jsx
> +          </BottomArea>
이건 styled component에서 before 사용법 검색해서 찾으면 될 것 같네요!

2023-08-04 06:55 UTC, Jake-Kim38 commented on src/components/InsuranceBox.jsx
> +          </BottomArea>
이거에 자꾸 매달리는게 맞는지는 모르겠지만..
형 말해주신대로 before나 after 적용해서 구분선을 만들려보려고 했는데
위치도 그렇고, 디자인적으로 뭔가 원하는대로 나오질 않아서.. 원래 썼던 방법은 쓰면 곤란할까요..?

2023-08-04 07:59 UTC, Bhanjo commented on src/components/InsuranceBox.jsx
> +          </BottomArea>
코드 퀄리티와 학습을 원한다면 divline을 직접 하나하나 넣어주는 하드코딩은 지양해주세요!

방법으로는 before와 같이 가상요소를 만들기, 표를 이용하기, grid이용하기 등 다양한 방법이 있어요

본인이 생각했을 때 이건 넘어가도 될 것 같다 싶으면 넘어가셔도 됩니다~

2023-08-05 06:37 UTC, Bhanjo commented on src/components/InsuranceBox.jsx
> +            </CostArea>
피그마를 보면 age, cost 등 구성이 똑같으니까 이걸 다른 컴포넌트로 공통화를 시키면 좋아보인다는 의미입니다!

2023-08-05 06:38 UTC, Bhanjo commented on src/components/InsuranceBox.jsx
> +  justify-content: space-around;
코드만 보면 지금 상황이 어떤지 모릅니다! 특히 css는 복잡하게 얽혀있어서 더욱 코드만 보고 잘 파악이 안 돼요
따라서 지금은 주의해서 써달라의 의미입니다!

2023-08-05 06:39 UTC, Bhanjo commented on src/styles/Theme.jsx
> +export const Theme = {
위에 하신 말씀이 맞아요~

2023-08-05 06:56 UTC, Jake-Kim38 commented on src/components/InsuranceBox.jsx
> +            </CostArea>
그렇다면 아래에 학수형이 말하신대로 StyledArea, StyledUnit...등등 공통 스타일을 만들어서 적용하면 되는걸까요??

2023-08-05 12:05 UTC, Bhanjo commented on src/components/InsuranceBox.jsx
> +            </CostArea>
styledComponent를 만들라는 의미가 아니라 `component`를 만들라는 의미입니다!
component와 styledComponent의 차이점을 인지해주세요!

2023-08-05 14:51 UTC, harksu approved these changes
네이밍에 관련된 고민, 태그에 대한 조금 더 시멘틱한 사용이 좋을 것 같습니다 :)

2023-08-05 14:51 UTC, harksu commented on src/components/InsuranceBox.jsx
> +  const { img, main, company, start, end, cost, type } = loanData;
무슨 start인지 무슨 end인지 main은 뭔지, type은 무슨 type인지 데이터에 관련된 props name이 다소 적합하지 않은 것 같습니다 
페이지 많아지면 나중에 이거 뭐였더라.. 이러면서 헷갈려요

2023-08-05 14:51 UTC, harksu commented on src/components/InsuranceBox.jsx
> +            <DivLine />
```suggestion
            <BreakLine />
```

2023-08-05 14:51 UTC, harksu commented on src/components/SmallButton.jsx
> +const SmallButton = ({ text, handleClick }) => {
import 넘어가고 한 줄 띄어주는게 보편적입니당 :)

2023-08-05 18:28 UTC, Bhanjo approved these changes
끝났다면 merge 해주세요~

2023-08-06 01:22 UTC, merged